package com.al3x.housing2.Enums;

import org.bukkit.Material;
import org.bukkit.attribute.Attribute;

public enum AttributeType implements EnumMaterial {
    GENERIC_ARMOR(Material.IRON_CHESTPLATE),
    GENERIC_ARMOR_TOUGHNESS(Material.DIAMOND_CHESTPLATE),
    GENERIC_ATTACK_DAMAGE(Material.DIAMOND_SWORD),
    GENERIC_ATTACK_KNOCKBACK(Material.WOODEN_SWORD),
    GENERIC_ATTACK_SPEED(Material.GOLDEN_SWORD),
    PLAYER_BLOCK_BREAK_SPEED(Material.DIAMOND_PICKAXE),
    PLAYER_BLOCK_INTERACTION_TIME(Material.WOODEN_SHOVEL),
    GENERIC_BURNING_TIME(Material.FLINT_AND_STEEL),
    PLAYER_ENTITY_INTERACTION_RANGE(Material.LEAD),
    GENERIC_EXPLOSION_KNOCKBACK_RESISTANCE(Material.TNT),
    PLAYER_FALL_DAMAGE_MULTIPLIER(Material.FEATHER),
    GENERIC_FLYING_SPEED(Material.ELYTRA),
    GENERIC_FOLLOW_RANGE(Material.NAME_TAG),
    GENERIC_GRAVITY(Material.GRAVEL),
    GENERIC_JUMP_STRENGTH(Material.SLIME_BLOCK),
    GENERIC_KNOCKBACK_RESISTANCE(Material.SHIELD),
    GENERIC_LUCK(Material.GOLD_NUGGET),
    GENERIC_MAX_ABSORPTION(Material.GOLDEN_APPLE),
    GENERIC_MAX_HEALTH(Material.GOLDEN_APPLE),
    PLAYER_MINING_EFFICIENCY(Material.DIAMOND_PICKAXE),
    GENERIC_MOVEMENT_SPEED(Material.DIAMOND_BOOTS),
    GENERIC_OXYGEN_BONUS(Material.WATER_BUCKET),
    GENERIC_SAFE_FALL_DISTANCE(Material.FEATHER),
    GENERIC_SCALE(Material.DIAMOND),
    PLAYER_SNEAKING_SPEED(Material.LEATHER_BOOTS),
    GENERIC_STEP_HEIGHT(Material.IRON_LEGGINGS),
    PLAYER_SUBMERGED_MINING_SPEED(Material.TRIDENT),
    PLAYER_SWEEPING_DAMAGE_RATIO(Material.DIAMOND_SWORD),
    GENERIC_WATER_MOVEMENT_EFFICIENCY(Material.GOLDEN_BOOTS);

    Material material;
    AttributeType(Material material) {
        this.material = material;
    }

    @Override
    public Material getMaterial() {
        return material;
    }
}
