name: Housing2
version: '1.0'
main: com.al3x.housing2.Main
api-version: '1.20'
authors: [ Al3x ]
depend: [Citizens]
commands:
  housing:
    usage: "/housing help"
    aliases: ["h"]
  home:
    usage: "/home [name]"
    aliases: ["house", "homes"]

  cancelinput:
    usage: "/cancelinput"
  testplaceholder:
    usage: "/testplaceholder <string>"
  placeholders:
    usage: "/placeholders [filter]"