enum class OldActionType(val actionName: String) {
    CONDITIONAL("Conditional Action"),
    CANCEL("Cancel Action"),
    CHANGE_PLAYER_GROUP("Change Player Group"),
    CHANGE_PLAYER_TEAM("Change Player Team"),
    KILL_PLAYER("Kill Player Action"),
    KILL_NPC("Kill NPC Action"),
    FULL_HEAL("Full Heal Action"),
    SET_VELOCITY("Set Velocity Action"),
    SEND_TITLE("Send Title Action"),
    ACTIONBAR("Actionbar Action"),
    RESET_INVENTORY("Reset Inventory Action"),
    CHANGE_MAX_HEALTH("Change Max Health Action"),
    GIVE_ITEM("Give Item Action"),
    REMOVE_ITEM("Remove Item Action"),
    CHAT("Chat Action"),
    APPLY_POTION("Apply Potion Effect Action"),
    CLEAR_POTION("Clear Potion Effect Action"),
    PLAYER_STAT("Player Stat Action"),
    NPC_STAT("NPC Stat Action"),
    GLOBAL_STAT("Global Stat Action"),
    TELEPORT("Teleport Action"),
    CLEAR_ENDERCHEST("Clear Enderchest Action"),
    PLAY_SOUND("Play Sound Action"),
    STOP_SOUND("Stop Sound Action"),
    SET_GAMEMODE("Set Gamemode Action"),
    CHANGE_HEALTH("Change Health Action"),
    CHANGE_HUNGER("Change Hunger Action"),
    RANDOM_ACTION("Random Action"),
    FUNCTION("Function Action"),
    APPLY_INVENTORY_LAYOUT("Apply Inventory Layout Action"),
    PAUSE_EXECUTION("Pause Action"),
    SHOW_BOSSBAR("Show Bossbar Action"),
    SET_HITDELAY("Set Hit Delay Action"),
    LAUNCH_PROJECTILE("Launch Projectile Action"),
    PARTICLE("Particle Action"),
    CHANGE_NPC_NAVIGATION("Change Npc Navigation Action"),
    CHANGE_PLAYER_DISPLAYNAME("Change Player Display Name Action"),
    CHANGE_NAMETAG("NameTag Action"),
    REPEAT("Repeat Action"),
    CLEAR_BOSSBAR("Clear Bossbars Action"),
    CLEAR_PLAYERSTATS("Clear Player Stats Action"),
    CLEAR_GLOBALSTATS("Clear Global Stats Action"),
    EXIT("Exit Action"),
    BREAK("Break Action"),
    CONTINUE("Continue Action"),
    DISPLAY_MENU("Display Menu Action"),
    CLOSE_MENU("Close Menu Action"),
    EXPLOSION("Explosion Action"),
    START_HOUSE_MUSIC("Start House Music Action"),
    STOP_HOUSE_MUSIC("Stop House Music Action"),
    CHANGE_PLAYER_ATTRIBUTE("Change Player Attribute Action"),
    CHANGE_NPC_ATTRIBUTE("Change NPC Attribute Action"),
    CHANGE_TIME("Change Time Action"),
    ATTACK_ENTITY("Attack Entity Action"),
    DROP_ITEM("Drop Item Action"),
    RUN_AS_NPC("Run As NPC Action"),
    HIDE_NPC("Hide NPC Action"),
    SHOW_NPC("Show NPC Action"),
    SWIM_CRAWL("Swim/Crawl Action"),
    TOGGLE_SIT("Toggle Sit Action"),
    SEND_TO_HOUSE("Send to House Action"),
    SET_VOICE_GROUP("Set Voice Group Action"),
    EDIT_VOICE_GROUP("Edit Voice Group Action"),
    EDIT_VISIBILITY("Edit Visibility Action"),
    EDIT_AUDIBILITY("Edit Audibility Action"),
    PROTOOLS_ACTION("Protools Action"),
    SPAWN_GHOST_BLOCK("Spawn Ghost Block"),
    SET_PLAYER_SLOT("Set Player Slot Action");
}