name: Gradle Package

on:
  push:
     branches: [ "*" ]
     paths-ignore:
       - "fabric/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.12'

    - name: Build with Gradle
      run: ./gradlew :paper:shadowJar

    - name: Publish Package
      run: ./gradlew publish
      env:
        COMMIT: ${{ github.sha }}
