name: Fabric Mod Build

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - "paper/**"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "paper/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
         gradle-version: '8.12'

    - name: Build with Gradle Wrapper
      run: ./gradlew :fabric:remapJar

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playground-mod-artifacts
        path: fabric/build/libs/
        retention-days: 14
