bot_key: ""
guild_id: ""
globalLimits: 2000
actionLimits:
  Particle Action: 100

# web
api_port: 8080
web_base: http://localhost:8080

# loader for slimeworld (mongo or file)
loader: file
mongo_uri: mongodb://localhost:27017
mongo_db: playground
