name: Housing2
version: '1.0'
main: com.al3x.housing2.Main
api-version: '1.21'
authors: [ Al3x ]
soft-depend: [PlaceholderAPI, ItemsAdder]
depend: [Citizens, ProtocolLib, NoteBlockAPI, packetevents, HeadDatabase]
loadbefore: [Citizens]
commands:
  staffalerts:
  broadcast:
    aliases: ["bc"]
  hub:
    aliases: ["lobby", "l"]
  visit:
  housing:
    aliases: ["h"]
  home:
    aliases: ["house", "homes"]
  setspawn:
  fly:
  cancelinput:
    usage: "/cancelinput"
  testplaceholder:
    usage: "/testplaceholder <string>"
  placeholders:
  edit:
  gamemode:
  wand:
    usage: "/wand"
    aliases: ["/", "wand", "housingwand"]
  set:
    aliases: ["/set"]
  sphere:
    aliases: ["/sphere"]
  replace:
    aliases: ["/replace"]
  undo:
    aliases: ["/undo"]
  WTFMap: